apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: eq5f472z0-nodejs
  janus-idp.io/tekton: eq5f472z0-nodejs
  backstage.io/kubernetes-id: eq5f472z0-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: eq5f472z0-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
